### ISSUE TITLE
Request timeout support

### ISSUE THREAD

**Issue by brightsparc** [gojko/minimal-request-promise#6]
The default request timeout is 2 minutes, would it be possible to pass configuration through to set this as part of the library: https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback

Or would you recommend using another promise provide with timeout capability (like bluebird)?

**Comment by gojko** [comment]
if you want to add a timeout option to the call args (similar to eg resolveErrors) and use it to set the request timeout, that sounds perfectly fine. submit a PR and I'll merge it.
